name: monolib_dart
description: A starting point for Dart libraries or applications.
version: 0.0.0
repository: https://github.com/TarasMazepa/monolib

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
