name: monolib_flutter
description: A collection of general purpose libraries for flutter projects
version: 0.0.0
homepage:

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
