name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: flutter-actions/setup-flutter@v4
        with:
          cache: true
          cache-sdk: true

      - run: dart pub get
        working-directory: monolib-dart

      - run: flutter pub get
        working-directory: monolib-flutter

      - run: dart format --output=none --set-exit-if-changed .
        working-directory: monolib-dart

      - run: dart format --output=none --set-exit-if-changed .
        working-directory: monolib-flutter

      - run: dart analyze --fatal-infos
        working-directory: monolib-dart

      - run: flutter analyze --fatal-infos
        working-directory: monolib-flutter

      - run: dart test
        working-directory: monolib-dart

      - run: flutter test
        working-directory: monolib-flutter
