name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: flutter-actions/setup-flutter@v4
        with:
          cache: true
          cache-sdk: true

      - run: dart pub get
        working-directory: monolib-dart

      - run: flutter pub get
        working-directory: monolib-flutter

      - run: dart format --output=none --set-exit-if-changed .
        id: format-check-dart
        working-directory: monolib-dart
        continue-on-error: true

      - run: dart format --output=none --set-exit-if-changed .
        id: format-check-flutter
        working-directory: monolib-flutter
        continue-on-error: true

      - uses: peter-evans/repository-dispatch@v3
        if: ${{ (steps.format-check-dart.outcome == 'failure' || steps.format-check-flutter.outcome == 'failure') && github.event_name == 'pull_request' }}
        with:
          token: ${{ secrets.PAT }}
          repository: TarasMazepa/monolib
          event-type: format-dart-code
          client-payload: '{"ref": "${{ github.head_ref }}"}'

      - run: dart format --output=none --set-exit-if-changed .
        if: steps.format-check-dart.outcome == 'failure'
        working-directory: monolib-dart

      - run: dart format --output=none --set-exit-if-changed .
        if: steps.format-check-flutter.outcome == 'failure'
        working-directory: monolib-flutter

      - run: dart analyze --fatal-infos
        working-directory: monolib-dart

      - run: flutter analyze --fatal-infos
        working-directory: monolib-flutter

      - run: dart test
        working-directory: monolib-dart

      - run: flutter test
        working-directory: monolib-flutter
