name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          cache: true
          cache-sdk: true

      - name: monolib-dart - dart pub get
        working-directory: monolib-dart
        run: dart pub get

      - name: monolib-dart - dart format
        working-directory: monolib-dart
        run: dart format --output=none --set-exit-if-changed .

      - name: monolib-dart - dart analyze
        working-directory: monolib-dart
        run: dart analyze --fatal-infos

      - name: monolib-dart - dart test
        working-directory: monolib-dart
        run: dart test

      - name: monolib-flutter - flutter pub get
        working-directory: monolib-flutter
        run: flutter pub get

      - name: monolib-flutter - dart format
        working-directory: monolib-flutter
        run: dart format --output=none --set-exit-if-changed .

      - name: monolib-flutter - flutter analyze
        working-directory: monolib-flutter
        run: flutter analyze --fatal-infos

      - name: monolib-flutter - flutter test
        working-directory: monolib-flutter
        run: flutter test
