name: dart-format.yml
on:
  workflow_dispatch:

jobs:
  dart-format:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: flutter-actions/setup-flutter@v4
        with:
          cache: true
          cache-sdk: true

      - run: dart format .
        working-directory: monolib-dart

      - run: dart format .
        working-directory: monolib-flutter

      - run: |
          if ! git diff --quiet; then
            branch_name=format-dart-code-in-${GITHUB_REF#refs/heads/}-branch-at-$(date -u +"%Y-%m-%dT%H-%M-%S")
            git config --global user.name 'stax'
            git config --global user.email 'stax@staxforgit.com'
            git checkout -b $branch_name
            git commit -a -m "Format dart code in ${GITHUB_REF#refs/heads/} branch"
            git push --set-upstream origin $branch_name
            gh pr merge $(gh pr create -B ${GITHUB_REF#refs/heads/} -f) --auto --squash
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT }}
