name: monolib-flutter.yml

on:
  push:
    branches: [ "main" ]
    paths:
      - 'monolib-flutter/**'
      - '.github/workflows/monolib-flutter.yml'
  pull_request:
    paths:
      - 'monolib-flutter/**'
      - '.github/workflows/monolib-flutter.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  monolib-flutter:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: monolib-flutter

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - run: flutter pub get

      - run: dart format --output=none --set-exit-if-changed .

      - run: flutter analyze --fatal-infos

      - run: flutter test
