name: pub-upgrade.yml

on:
  pull_request:
    paths:
      - 'monolib-dart/pubspec.yaml'
      - 'monolib-flutter/pubspec.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pub-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          cache: true
          cache-sdk: true

      - run: dart pub upgrade
        working-directory: monolib-dart

      - run: flutter pub upgrade
        working-directory: monolib-flutter

      - name: Commit and push changes
        run: |
          git config --global user.name 'monorepohub'
          git config --global user.email 'git@monorepohub.com'
          git add -f monolib-dart/pubspec.lock monolib-flutter/pubspec.lock
          git diff --staged --quiet || (git commit -m "chore: run pub upgrade" && git push)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
