name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - 'monolib-dart/pubspec.yaml'
      - 'monolib-flutter/pubspec.yaml'

jobs:
  publish_dart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish monolib-dart
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: monolib-dart

  publish_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish monolib-flutter
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: monolib-flutter
          flutter: true
