name: tag-monolib-flutter.yml

on:
  push:
    branches:
      - main
    paths:
      - 'monolib-flutter/pubspec.yaml'

jobs:
  tag-monolib-flutter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Need at least 2 commits to compare with previous

      - run: .github/scripts/check-version-and-tag.sh "monolib-flutter"
