name: tag-monolib-flutter

on:
  push:
    branches:
      - main
    paths:
      - 'monolib-flutter/pubspec.yaml'

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Need at least 2 commits to compare with previous

      - name: Check version change and tag
        run: .github/scripts/check-version-and-tag.sh "monolib-flutter"
